// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /home/web/live-sandhosts/mono-v140/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar dmem, imem, xreg;


//
// Signals declared top-level.
//

// For |cpu$br_target_pc.
logic [31:0] CPU_br_target_pc_a2,
             CPU_br_target_pc_a3;

// For |cpu$dec_bits.
logic [10:0] CPU_dec_bits_a2;

// For |cpu$dmem_addr.
logic [3:0] CPU_dmem_addr_a4;

// For |cpu$dmem_rd_data.
logic [31:0] CPU_dmem_rd_data_a4,
             CPU_dmem_rd_data_a5;

// For |cpu$dmem_rd_en.
logic CPU_dmem_rd_en_a4;

// For |cpu$dmem_wr_data.
logic [31:0] CPU_dmem_wr_data_a4;

// For |cpu$dmem_wr_en.
logic CPU_dmem_wr_en_a4;

// For |cpu$funct3.
logic [2:0] CPU_funct3_a1,
            CPU_funct3_a2;

// For |cpu$funct7.
logic [6:0] CPU_funct7_a1;
logic [5:5] CPU_funct7_a2;

// For |cpu$imem_rd_addr.
logic [4-1:0] CPU_imem_rd_addr_a1;

// For |cpu$imem_rd_data.
logic [31:0] CPU_imem_rd_data_a1;

// For |cpu$imem_rd_en.
logic CPU_imem_rd_en_a1;

// For |cpu$imm.
logic [31:0] CPU_imm_a1,
             CPU_imm_a2,
             CPU_imm_a3;

// For |cpu$inc_pc.
logic [31:0] CPU_inc_pc_a2,
             CPU_inc_pc_a3;

// For |cpu$instr.
logic [31:0] CPU_instr_a1;

// For |cpu$is_add.
logic CPU_is_add_a2,
      CPU_is_add_a3;

// For |cpu$is_addi.
logic CPU_is_addi_a2,
      CPU_is_addi_a3;

// For |cpu$is_b_instr.
logic CPU_is_b_instr_a1;

// For |cpu$is_beq.
logic CPU_is_beq_a2,
      CPU_is_beq_a3;

// For |cpu$is_bge.
logic CPU_is_bge_a2,
      CPU_is_bge_a3;

// For |cpu$is_bgeu.
logic CPU_is_bgeu_a2,
      CPU_is_bgeu_a3;

// For |cpu$is_blt.
logic CPU_is_blt_a2,
      CPU_is_blt_a3;

// For |cpu$is_bltu.
logic CPU_is_bltu_a2,
      CPU_is_bltu_a3;

// For |cpu$is_bne.
logic CPU_is_bne_a2,
      CPU_is_bne_a3;

// For |cpu$is_i_instr.
logic CPU_is_i_instr_a1;

// For |cpu$is_j_instr.
logic CPU_is_j_instr_a1;

// For |cpu$is_jal.
logic CPU_is_jal_a2,
      CPU_is_jal_a3;

// For |cpu$is_jalr.
logic CPU_is_jalr_a2,
      CPU_is_jalr_a3;

// For |cpu$is_jump.
logic CPU_is_jump_a2,
      CPU_is_jump_a3;

// For |cpu$is_load.
logic CPU_is_load_a2,
      CPU_is_load_a3,
      CPU_is_load_a4;

// For |cpu$is_r_instr.
logic CPU_is_r_instr_a1;

// For |cpu$is_s_instr.
logic CPU_is_s_instr_a1,
      CPU_is_s_instr_a2,
      CPU_is_s_instr_a3,
      CPU_is_s_instr_a4;

// For |cpu$is_u_instr.
logic CPU_is_u_instr_a1;

// For |cpu$jalr_target_pc.
logic [31:0] CPU_jalr_target_pc_a2,
             CPU_jalr_target_pc_a3;

// For |cpu$ld_data.
logic [31:0] CPU_ld_data_a5;

// For |cpu$opcode.
logic [6:0] CPU_opcode_a1,
            CPU_opcode_a2;

// For |cpu$pc.
logic [31:0] CPU_pc_a0,
             CPU_pc_a1,
             CPU_pc_a2;

// For |cpu$rd.
logic [4:0] CPU_rd_a1,
            CPU_rd_a2,
            CPU_rd_a3;

// For |cpu$rd_valid.
logic CPU_rd_valid_a1,
      CPU_rd_valid_a2,
      CPU_rd_valid_a3;

// For |cpu$reset.
logic CPU_reset_a0,
      CPU_reset_a1,
      CPU_reset_a2,
      CPU_reset_a3,
      CPU_reset_a4;

// For |cpu$result.
logic [31:0] CPU_result_a3;
logic [5:2] CPU_result_a4;

// For |cpu$rf_rd_data1.
logic [31:0] CPU_rf_rd_data1_a2;

// For |cpu$rf_rd_data2.
logic [31:0] CPU_rf_rd_data2_a2;

// For |cpu$rf_rd_en1.
logic CPU_rf_rd_en1_a2;

// For |cpu$rf_rd_en2.
logic CPU_rf_rd_en2_a2;

// For |cpu$rf_rd_index1.
logic [4:0] CPU_rf_rd_index1_a2;

// For |cpu$rf_rd_index2.
logic [4:0] CPU_rf_rd_index2_a2;

// For |cpu$rf_wr_data.
logic [31:0] CPU_rf_wr_data_a3;

// For |cpu$rf_wr_en.
logic CPU_rf_wr_en_a3;

// For |cpu$rf_wr_index.
logic [4:0] CPU_rf_wr_index_a3;

// For |cpu$rs1.
logic [4:0] CPU_rs1_a1,
            CPU_rs1_a2;

// For |cpu$rs1_valid.
logic CPU_rs1_valid_a1,
      CPU_rs1_valid_a2;

// For |cpu$rs2.
logic [4:0] CPU_rs2_a1,
            CPU_rs2_a2;

// For |cpu$rs2_valid.
logic CPU_rs2_valid_a1,
      CPU_rs2_valid_a2;

// For |cpu$src1_value.
logic [31:0] CPU_src1_value_a2,
             CPU_src1_value_a3;

// For |cpu$src2_value.
logic [31:0] CPU_src2_value_a2,
             CPU_src2_value_a3,
             CPU_src2_value_a4;

// For |cpu$taken_branch.
logic CPU_taken_branch_a3;

// For |cpu$valid.
logic CPU_valid_a3,
      CPU_valid_a4;

// For |cpu$valid_jump.
logic CPU_valid_jump_a3,
      CPU_valid_jump_a4,
      CPU_valid_jump_a5;

// For |cpu$valid_taken_branch.
logic CPU_valid_taken_branch_a3,
      CPU_valid_taken_branch_a4,
      CPU_valid_taken_branch_a5;

// For |cpu/dmem$value.
logic [31:0] CPU_Dmem_value_a4 [15:0],
             CPU_Dmem_value_a5 [15:0];

// For |cpu/imem$instr.
logic [31:0] CPU_Imem_instr_a1 [9:0];

// For |cpu/xreg$value.
logic [31:0] CPU_Xreg_value_a3 [31:0],
             CPU_Xreg_value_a4 [31:0],
             CPU_Xreg_value_a5 [31:0];




   //
   // Scope: |cpu
   //

      // Staging of $br_target_pc.
      always_ff @(posedge clk) CPU_br_target_pc_a3[31:0] <= CPU_br_target_pc_a2[31:0];

      // Staging of $dmem_rd_data.
      always_ff @(posedge clk) CPU_dmem_rd_data_a5[31:0] <= CPU_dmem_rd_data_a4[31:0];

      // Staging of $funct3.
      always_ff @(posedge clk) CPU_funct3_a2[2:0] <= CPU_funct3_a1[2:0];

      // Staging of $funct7.
      always_ff @(posedge clk) CPU_funct7_a2[5] <= CPU_funct7_a1[5];

      // Staging of $imm.
      always_ff @(posedge clk) CPU_imm_a2[31:0] <= CPU_imm_a1[31:0];
      always_ff @(posedge clk) CPU_imm_a3[31:0] <= CPU_imm_a2[31:0];

      // Staging of $inc_pc.
      always_ff @(posedge clk) CPU_inc_pc_a3[31:0] <= CPU_inc_pc_a2[31:0];

      // Staging of $is_add.
      always_ff @(posedge clk) CPU_is_add_a3 <= CPU_is_add_a2;

      // Staging of $is_addi.
      always_ff @(posedge clk) CPU_is_addi_a3 <= CPU_is_addi_a2;

      // Staging of $is_beq.
      always_ff @(posedge clk) CPU_is_beq_a3 <= CPU_is_beq_a2;

      // Staging of $is_bge.
      always_ff @(posedge clk) CPU_is_bge_a3 <= CPU_is_bge_a2;

      // Staging of $is_bgeu.
      always_ff @(posedge clk) CPU_is_bgeu_a3 <= CPU_is_bgeu_a2;

      // Staging of $is_blt.
      always_ff @(posedge clk) CPU_is_blt_a3 <= CPU_is_blt_a2;

      // Staging of $is_bltu.
      always_ff @(posedge clk) CPU_is_bltu_a3 <= CPU_is_bltu_a2;

      // Staging of $is_bne.
      always_ff @(posedge clk) CPU_is_bne_a3 <= CPU_is_bne_a2;

      // Staging of $is_jal.
      always_ff @(posedge clk) CPU_is_jal_a3 <= CPU_is_jal_a2;

      // Staging of $is_jalr.
      always_ff @(posedge clk) CPU_is_jalr_a3 <= CPU_is_jalr_a2;

      // Staging of $is_jump.
      always_ff @(posedge clk) CPU_is_jump_a3 <= CPU_is_jump_a2;

      // Staging of $is_load.
      always_ff @(posedge clk) CPU_is_load_a3 <= CPU_is_load_a2;
      always_ff @(posedge clk) CPU_is_load_a4 <= CPU_is_load_a3;

      // Staging of $is_s_instr.
      always_ff @(posedge clk) CPU_is_s_instr_a2 <= CPU_is_s_instr_a1;
      always_ff @(posedge clk) CPU_is_s_instr_a3 <= CPU_is_s_instr_a2;
      always_ff @(posedge clk) CPU_is_s_instr_a4 <= CPU_is_s_instr_a3;

      // Staging of $jalr_target_pc.
      always_ff @(posedge clk) CPU_jalr_target_pc_a3[31:0] <= CPU_jalr_target_pc_a2[31:0];

      // Staging of $opcode.
      always_ff @(posedge clk) CPU_opcode_a2[6:0] <= CPU_opcode_a1[6:0];

      // Staging of $pc.
      always_ff @(posedge clk) CPU_pc_a1[31:0] <= CPU_pc_a0[31:0];
      always_ff @(posedge clk) CPU_pc_a2[31:0] <= CPU_pc_a1[31:0];

      // Staging of $rd.
      always_ff @(posedge clk) CPU_rd_a2[4:0] <= CPU_rd_a1[4:0];
      always_ff @(posedge clk) CPU_rd_a3[4:0] <= CPU_rd_a2[4:0];

      // Staging of $rd_valid.
      always_ff @(posedge clk) CPU_rd_valid_a2 <= CPU_rd_valid_a1;
      always_ff @(posedge clk) CPU_rd_valid_a3 <= CPU_rd_valid_a2;

      // Staging of $reset.
      always_ff @(posedge clk) CPU_reset_a1 <= CPU_reset_a0;
      always_ff @(posedge clk) CPU_reset_a2 <= CPU_reset_a1;
      always_ff @(posedge clk) CPU_reset_a3 <= CPU_reset_a2;
      always_ff @(posedge clk) CPU_reset_a4 <= CPU_reset_a3;

      // Staging of $result.
      always_ff @(posedge clk) CPU_result_a4[5:2] <= CPU_result_a3[5:2];

      // Staging of $rs1.
      always_ff @(posedge clk) CPU_rs1_a2[4:0] <= CPU_rs1_a1[4:0];

      // Staging of $rs1_valid.
      always_ff @(posedge clk) CPU_rs1_valid_a2 <= CPU_rs1_valid_a1;

      // Staging of $rs2.
      always_ff @(posedge clk) CPU_rs2_a2[4:0] <= CPU_rs2_a1[4:0];

      // Staging of $rs2_valid.
      always_ff @(posedge clk) CPU_rs2_valid_a2 <= CPU_rs2_valid_a1;

      // Staging of $src1_value.
      always_ff @(posedge clk) CPU_src1_value_a3[31:0] <= CPU_src1_value_a2[31:0];

      // Staging of $src2_value.
      always_ff @(posedge clk) CPU_src2_value_a3[31:0] <= CPU_src2_value_a2[31:0];
      always_ff @(posedge clk) CPU_src2_value_a4[31:0] <= CPU_src2_value_a3[31:0];

      // Staging of $valid.
      always_ff @(posedge clk) CPU_valid_a4 <= CPU_valid_a3;

      // Staging of $valid_jump.
      always_ff @(posedge clk) CPU_valid_jump_a4 <= CPU_valid_jump_a3;
      always_ff @(posedge clk) CPU_valid_jump_a5 <= CPU_valid_jump_a4;

      // Staging of $valid_taken_branch.
      always_ff @(posedge clk) CPU_valid_taken_branch_a4 <= CPU_valid_taken_branch_a3;
      always_ff @(posedge clk) CPU_valid_taken_branch_a5 <= CPU_valid_taken_branch_a4;


      //
      // Scope: /dmem[15:0]
      //
      for (dmem = 0; dmem <= 15; dmem++) begin : L1gen_CPU_Dmem
         // Staging of $value.
         always_ff @(posedge clk) CPU_Dmem_value_a5[dmem][31:0] <= CPU_Dmem_value_a4[dmem][31:0];

      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_CPU_Xreg
         // Staging of $value.
         always_ff @(posedge clk) CPU_Xreg_value_a4[xreg][31:0] <= CPU_Xreg_value_a3[xreg][31:0];
         always_ff @(posedge clk) CPU_Xreg_value_a5[xreg][31:0] <= CPU_Xreg_value_a4[xreg][31:0];

      end





//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS


      //
      // Scope: |cpu
      //
      if (1) begin : \|cpu 
         logic [31:0] \/@2$br_target_pc ;
         assign \/@2$br_target_pc = CPU_br_target_pc_a2;
         logic [10:0] \/@2$dec_bits ;
         assign \/@2$dec_bits = CPU_dec_bits_a2;
         logic [3:0] \/@4$dmem_addr ;
         assign \/@4$dmem_addr = CPU_dmem_addr_a4;
         logic [31:0] \/?$dmem_rd_en@4$dmem_rd_data ;
         assign \/?$dmem_rd_en@4$dmem_rd_data = CPU_dmem_rd_data_a4;
         logic  \/@4$dmem_rd_en ;
         assign \/@4$dmem_rd_en = CPU_dmem_rd_en_a4;
         logic [31:0] \/@4$dmem_wr_data ;
         assign \/@4$dmem_wr_data = CPU_dmem_wr_data_a4;
         logic  \/@4$dmem_wr_en ;
         assign \/@4$dmem_wr_en = CPU_dmem_wr_en_a4;
         logic [2:0] \/@1$funct3 ;
         assign \/@1$funct3 = CPU_funct3_a1;
         logic [6:0] \/@1$funct7 ;
         assign \/@1$funct7 = CPU_funct7_a1;
         logic [4-1:0] \/@1$imem_rd_addr ;
         assign \/@1$imem_rd_addr = CPU_imem_rd_addr_a1;
         logic [31:0] \/?$imem_rd_en@1$imem_rd_data ;
         assign \/?$imem_rd_en@1$imem_rd_data = CPU_imem_rd_data_a1;
         logic  \/@1$imem_rd_en ;
         assign \/@1$imem_rd_en = CPU_imem_rd_en_a1;
         logic [31:0] \/@1$imm ;
         assign \/@1$imm = CPU_imm_a1;
         logic [31:0] \/@2$inc_pc ;
         assign \/@2$inc_pc = CPU_inc_pc_a2;
         logic [31:0] \/@1$instr ;
         assign \/@1$instr = CPU_instr_a1;
         logic  \/@2$is_add ;
         assign \/@2$is_add = CPU_is_add_a2;
         logic  \/@2$is_addi ;
         assign \/@2$is_addi = CPU_is_addi_a2;
         logic  \/@1$is_b_instr ;
         assign \/@1$is_b_instr = CPU_is_b_instr_a1;
         logic  \/@2$is_beq ;
         assign \/@2$is_beq = CPU_is_beq_a2;
         logic  \/@2$is_bge ;
         assign \/@2$is_bge = CPU_is_bge_a2;
         logic  \/@2$is_bgeu ;
         assign \/@2$is_bgeu = CPU_is_bgeu_a2;
         logic  \/@2$is_blt ;
         assign \/@2$is_blt = CPU_is_blt_a2;
         logic  \/@2$is_bltu ;
         assign \/@2$is_bltu = CPU_is_bltu_a2;
         logic  \/@2$is_bne ;
         assign \/@2$is_bne = CPU_is_bne_a2;
         logic  \/@1$is_i_instr ;
         assign \/@1$is_i_instr = CPU_is_i_instr_a1;
         logic  \/@1$is_j_instr ;
         assign \/@1$is_j_instr = CPU_is_j_instr_a1;
         logic  \/@2$is_jal ;
         assign \/@2$is_jal = CPU_is_jal_a2;
         logic  \/@2$is_jalr ;
         assign \/@2$is_jalr = CPU_is_jalr_a2;
         logic  \/@2$is_jump ;
         assign \/@2$is_jump = CPU_is_jump_a2;
         logic  \/@2$is_load ;
         assign \/@2$is_load = CPU_is_load_a2;
         logic  \/@1$is_r_instr ;
         assign \/@1$is_r_instr = CPU_is_r_instr_a1;
         logic  \/@1$is_s_instr ;
         assign \/@1$is_s_instr = CPU_is_s_instr_a1;
         logic  \/@1$is_u_instr ;
         assign \/@1$is_u_instr = CPU_is_u_instr_a1;
         logic [31:0] \/@2$jalr_target_pc ;
         assign \/@2$jalr_target_pc = CPU_jalr_target_pc_a2;
         logic [31:0] \/@5$ld_data ;
         assign \/@5$ld_data = CPU_ld_data_a5;
         logic [6:0] \/@1$opcode ;
         assign \/@1$opcode = CPU_opcode_a1;
         logic [31:0] \/@0$pc ;
         assign \/@0$pc = CPU_pc_a0;
         logic [4:0] \/@1$rd ;
         assign \/@1$rd = CPU_rd_a1;
         logic  \/@1$rd_valid ;
         assign \/@1$rd_valid = CPU_rd_valid_a1;
         logic  \/@0$reset ;
         assign \/@0$reset = CPU_reset_a0;
         logic [31:0] \/@3$result ;
         assign \/@3$result = CPU_result_a3;
         logic [31:0] \/?$rf_rd_en1@2$rf_rd_data1 ;
         assign \/?$rf_rd_en1@2$rf_rd_data1 = CPU_rf_rd_data1_a2;
         logic [31:0] \/?$rf_rd_en2@2$rf_rd_data2 ;
         assign \/?$rf_rd_en2@2$rf_rd_data2 = CPU_rf_rd_data2_a2;
         logic  \/@2$rf_rd_en1 ;
         assign \/@2$rf_rd_en1 = CPU_rf_rd_en1_a2;
         logic  \/@2$rf_rd_en2 ;
         assign \/@2$rf_rd_en2 = CPU_rf_rd_en2_a2;
         logic [4:0] \/@2$rf_rd_index1 ;
         assign \/@2$rf_rd_index1 = CPU_rf_rd_index1_a2;
         logic [4:0] \/@2$rf_rd_index2 ;
         assign \/@2$rf_rd_index2 = CPU_rf_rd_index2_a2;
         logic [31:0] \/@3$rf_wr_data ;
         assign \/@3$rf_wr_data = CPU_rf_wr_data_a3;
         logic  \/@3$rf_wr_en ;
         assign \/@3$rf_wr_en = CPU_rf_wr_en_a3;
         logic [4:0] \/@3$rf_wr_index ;
         assign \/@3$rf_wr_index = CPU_rf_wr_index_a3;
         logic [4:0] \/@1$rs1 ;
         assign \/@1$rs1 = CPU_rs1_a1;
         logic  \/@1$rs1_valid ;
         assign \/@1$rs1_valid = CPU_rs1_valid_a1;
         logic [4:0] \/@1$rs2 ;
         assign \/@1$rs2 = CPU_rs2_a1;
         logic  \/@1$rs2_valid ;
         assign \/@1$rs2_valid = CPU_rs2_valid_a1;
         logic [31:0] \/@2$src1_value ;
         assign \/@2$src1_value = CPU_src1_value_a2;
         logic [31:0] \/@2$src2_value ;
         assign \/@2$src2_value = CPU_src2_value_a2;
         logic  \/@3$taken_branch ;
         assign \/@3$taken_branch = CPU_taken_branch_a3;
         logic  \/@3$valid ;
         assign \/@3$valid = CPU_valid_a3;
         logic  \/@3$valid_jump ;
         assign \/@3$valid_jump = CPU_valid_jump_a3;
         logic  \/@3$valid_taken_branch ;
         assign \/@3$valid_taken_branch = CPU_valid_taken_branch_a3;

         //
         // Scope: /dmem[15:0]
         //
         for (dmem = 0; dmem <= 15; dmem++) begin : \/dmem 
            logic [31:0] \//@4$value ;
            assign \//@4$value = CPU_Dmem_value_a4[dmem];
            logic  \//@4$wr ;
            assign \//@4$wr = L1_CPU_Dmem[dmem].L1_wr_a4;
         end

         //
         // Scope: /imem[9:0]
         //
         for (imem = 0; imem <= 9; imem++) begin : \/imem 
            logic [31:0] \//@1$instr ;
            assign \//@1$instr = CPU_Imem_instr_a1[imem];
         end

         //
         // Scope: /xreg[31:0]
         //
         for (xreg = 0; xreg <= 31; xreg++) begin : \/xreg 
            logic [31:0] \//@3$value ;
            assign \//@3$value = CPU_Xreg_value_a3[xreg];
            logic  \//@3$wr ;
            assign \//@3$wr = L1_CPU_Xreg[xreg].L1_wr_a3;
         end
      end


   end

